export const PRODUCT_CATEGORIES = [
  "Dietary Supplement",
  "Functional Food",
  "Food",
  "Beverage",
  "Cosmetic",
  "OTC Drug",
  "Prescription Drug",
  "Medical Device",
  "Therapeutic Good",
  "Pet Food",
  "Pet Supplement",
  "Pet Care",
  "Pet Pesticide",
  "Animal Health",
  "Animal Supplement",
  "Household Cleaner",
  "Household Product",
  "Pesticide",
  "Consumer Product",
  "Consumer Electronics",
  "Home Appliance",
  "Children's Product",
  "Children's Food",
  "Children's Supplement",
  "Children's Software",
  "Baby Product",
  "Alcohol Beverage",
  "Tobacco Product",
  "Financial Service",
  "Software / AI",
  "Software",
  "Health Technology",
  "Personal Care",
  "Fitness Equipment",
  "Fitness Service",
  "Safety Equipment",
  "Apparel",
  "Footwear",
  "Furniture",
  "Other",
] as const;

export const MARKET_OPTIONS = [
  "United States",
  "European Union",
  "United Kingdom",
  "India",
  "Canada",
  "Australia",
] as const;

export const CATEGORY_TOPICS: Record<string, string[]> = {
  "Dietary Supplement": ["supplement", "health claim", "structure/function", "label", "ingredient", "substantiation"],
  "Functional Food": ["food", "nutrition", "health claim", "label", "organic"],
  Food: ["food", "nutrition", "label", "organic", "bioengineered"],
  Beverage: ["food", "beverage", "nutrition", "alcohol", "label"],
  Cosmetic: ["cosmetic", "beauty", "skin", "label", "drug claim"],
  "OTC Drug": ["drug", "therapeutic", "health claim", "label", "advertising"],
  "Prescription Drug": ["prescription", "drug", "promotion", "fair balance", "off-label"],
  "Medical Device": ["medical device", "diagnostic", "therapeutic", "label", "intended use"],
  "Therapeutic Good": ["therapeutic", "medicine", "medical device", "advertising"],
  "Pet Food": ["animal food", "pet food", "veterinary", "label", "disease claim"],
  "Pet Supplement": ["animal food", "pet food", "veterinary", "health claim"],
  "Pet Care": ["animal", "veterinary", "pesticide", "health claim"],
  "Pet Pesticide": ["animal", "pesticide", "efficacy", "label"],
  "Animal Health": ["animal", "veterinary", "drug", "promotion"],
  "Animal Supplement": ["animal food", "veterinary", "health claim", "label"],
  "Household Cleaner": ["cleaner", "antimicrobial", "disinfect", "pesticide", "environmental"],
  "Household Product": ["consumer product", "safety", "environmental", "label"],
  Pesticide: ["pesticide", "antimicrobial", "label", "efficacy", "environmental"],
  "Consumer Product": ["consumer product", "safety", "label", "environmental"],
  "Consumer Electronics": ["consumer product", "safety", "advertising"],
  "Home Appliance": ["consumer product", "safety", "advertising", "environmental"],
  "Children's Product": ["children", "toy", "choking", "safety", "tracking label"],
  "Children's Food": ["children", "food", "nutrition", "label"],
  "Children's Supplement": ["children", "supplement", "health claim", "label"],
  "Children's Software": ["children", "software", "advertising", "safety"],
  "Baby Product": ["children", "safety", "label", "health claim"],
  "Alcohol Beverage": ["alcohol", "beverage", "advertising", "health claim", "label"],
  "Tobacco Product": ["tobacco", "warning", "modified risk", "advertising"],
  "Financial Service": ["financial", "credit", "mortgage", "deposit", "advertising"],
  "Software / AI": ["software", "AI", "automated", "advertising", "substantiation"],
  Software: ["software", "AI", "advertising", "substantiation"],
  "Health Technology": ["software", "medical device", "health claim", "advertising"],
  "Personal Care": ["cosmetic", "beauty", "skin", "label"],
  "Fitness Equipment": ["consumer product", "safety", "advertising"],
  "Fitness Service": ["advertising", "health claim", "substantiation"],
  "Safety Equipment": ["consumer product", "safety", "label"],
  Apparel: ["consumer product", "advertising", "environmental"],
  Footwear: ["consumer product", "advertising", "safety"],
  Furniture: ["consumer product", "safety", "advertising"],
  Other: ["advertising", "substantiation", "consumer protection"],
};

export function marketKey(market: string) {
  if (/india|fssai/i.test(market)) return "India";
  if (/europe|eu\b/i.test(market)) return "European Union";
  if (/united kingdom|uk\b|britain/i.test(market)) return "United Kingdom";
  if (/canada/i.test(market)) return "Canada";
  if (/australia/i.test(market)) return "Australia";
  return "United States";
}
