/** Auto-generated by scripts/train-copilot-model.ts — do not edit manually. */

export const COPILOT_TRAINING = {
  "generatedAt": "2026-06-12T20:06:43.391Z",
  "totalCases": 1000,
  "classificationAccuracy": "1000/1000",
  "rewriteSafety": "360/360",
  "copilotFeatureTests": "4/4",
  "topPatterns": [
    {
      "phrase": "guaranteed",
      "severity": "medium",
      "hits": 70,
      "categories": [
        "Beverage",
        "Animal Supplement",
        "Children's Software",
        "Footwear",
        "Fitness Service"
      ]
    },
    {
      "phrase": "cures",
      "severity": "high",
      "hits": 60,
      "categories": [
        "Food",
        "Health Technology",
        "Pet Supplement",
        "Drug",
        "Furniture"
      ]
    },
    {
      "phrase": "prevents",
      "severity": "high",
      "hits": 60,
      "categories": [
        "Beverage",
        "Cosmetic",
        "Health Technology",
        "Pesticide",
        "Pet Pesticide"
      ]
    },
    {
      "phrase": "treats",
      "severity": "high",
      "hits": 40,
      "categories": [
        "Dietary Supplement",
        "Cosmetic",
        "Pet Care",
        "Baby Product"
      ]
    },
    {
      "phrase": "clinically proven",
      "severity": "medium",
      "hits": 40,
      "categories": [
        "Dietary Supplement",
        "Cosmetic",
        "Medical Device",
        "Software"
      ]
    },
    {
      "phrase": "no side effects",
      "severity": "high",
      "hits": 40,
      "categories": [
        "Dietary Supplement"
      ]
    },
    {
      "phrase": "eliminates",
      "severity": "high",
      "hits": 30,
      "categories": [
        "Dietary Supplement",
        "Medical Device",
        "Home Appliance"
      ]
    },
    {
      "phrase": "disease",
      "severity": "high",
      "hits": 30,
      "categories": [
        "Food",
        "Medical Device",
        "Pesticide"
      ]
    },
    {
      "phrase": "depression",
      "severity": "high",
      "hits": 20,
      "categories": [
        "Dietary Supplement",
        "Health Technology"
      ]
    },
    {
      "phrase": "reverses",
      "severity": "high",
      "hits": 20,
      "categories": [
        "Dietary Supplement",
        "Cosmetic"
      ]
    },
    {
      "phrase": "diabetes",
      "severity": "high",
      "hits": 20,
      "categories": [
        "Dietary Supplement"
      ]
    },
    {
      "phrase": "arthritis",
      "severity": "high",
      "hits": 20,
      "categories": [
        "Dietary Supplement",
        "Pet Supplement"
      ]
    },
    {
      "phrase": "100% safe",
      "severity": "medium",
      "hits": 20,
      "categories": [
        "Food",
        "Consumer Electronics"
      ]
    },
    {
      "phrase": "100% safe",
      "severity": "high",
      "hits": 20,
      "categories": [
        "Food",
        "Consumer Electronics"
      ]
    },
    {
      "phrase": "weight loss",
      "severity": "medium",
      "hits": 20,
      "categories": [
        "Beverage",
        "Fitness Service"
      ]
    },
    {
      "phrase": "cancer",
      "severity": "high",
      "hits": 20,
      "categories": [
        "Cosmetic",
        "Home Appliance"
      ]
    },
    {
      "phrase": "diagnoses",
      "severity": "high",
      "hits": 20,
      "categories": [
        "Medical Device"
      ]
    },
    {
      "phrase": "chronic pain",
      "severity": "high",
      "hits": 20,
      "categories": [
        "Medical Device",
        "Dietary Supplement"
      ]
    },
    {
      "phrase": "performance",
      "severity": "medium",
      "hits": 20,
      "categories": [
        "Medical Device",
        "Animal Supplement"
      ]
    },
    {
      "phrase": "kills",
      "severity": "high",
      "hits": 20,
      "categories": [
        "Household Cleaner",
        "Pet Pesticide"
      ]
    },
    {
      "phrase": "viruses",
      "severity": "high",
      "hits": 20,
      "categories": [
        "Household Cleaner",
        "Home Appliance"
      ]
    },
    {
      "phrase": "non-toxic",
      "severity": "medium",
      "hits": 20,
      "categories": [
        "Household Cleaner"
      ]
    },
    {
      "phrase": "eco-friendly",
      "severity": "medium",
      "hits": 20,
      "categories": [
        "Household Cleaner"
      ]
    },
    {
      "phrase": "biodegradable",
      "severity": "medium",
      "hits": 20,
      "categories": [
        "Household Product"
      ]
    },
    {
      "phrase": "scientifically proven",
      "severity": "medium",
      "hits": 20,
      "categories": [
        "Cosmetic"
      ]
    }
  ]
} as const;
