"""Public prospect seed data for ClaimGuard outreach (verify contacts before sending)."""

from __future__ import annotations

from typing import TypedDict


class Prospect(TypedDict):
    business_name: str
    sector: str
    product_type: str
    website: str
    email: str
    phone: str
    instagram: str
    linkedin: str
    tiktok: str
    reddit: str
    source: str
    outreach_angle: str


def _row(
    name: str,
    sector: str,
    product: str,
    website: str = "",
    email: str = "",
    phone: str = "",
    instagram: str = "",
    linkedin: str = "",
    tiktok: str = "",
    reddit: str = "",
    source: str = "Public brand / industry research",
    angle: str = "",
) -> Prospect:
    domain = website.replace("https://", "").replace("http://", "").split("/")[0] if website else ""
    default_angle = (
        f"Scan {product.lower()} marketing copy for FDA/FTC/FSSAI risk before the next campaign launch."
    )
    return {
        "business_name": name,
        "sector": sector,
        "product_type": product,
        "website": website,
        "email": email,
        "phone": phone,
        "instagram": instagram or (f"@{domain.split('.')[0]}" if domain and len(domain.split('.')[0]) > 2 else ""),
        "linkedin": linkedin or (f"https://www.linkedin.com/company/{domain.split('.')[0]}" if domain else ""),
        "tiktok": tiktok,
        "reddit": reddit,
        "source": source,
        "outreach_angle": angle or default_angle,
    }


# fmt: off
BRANDS: list[tuple] = [
    # US DTC Supplements & Wellness (websites publicly known)
    ("Ritual", "Dietary Supplements", "Women's Multivitamin", "https://ritual.com"),
    ("Athletic Greens (AG1)", "Dietary Supplements", "Greens Powder", "https://drinkag1.com"),
    ("Seed", "Dietary Supplements", "Probiotic", "https://seed.com"),
    ("Thorne", "Dietary Supplements", "Professional Supplements", "https://thorne.com"),
    ("Momentous", "Sports Nutrition", "Performance Supplements", "https://livemomentous.com"),
    ("Transparent Labs", "Sports Nutrition", "Pre-Workout", "https://transparentlabs.com"),
    ("Legion Athletics", "Sports Nutrition", "Whey Protein", "https://legionathletics.com"),
    ("Kaged", "Sports Nutrition", "BCAA / Pre-Workout", "https://kaged.com"),
    ("Ghost Lifestyle", "Sports Nutrition", "Lifestyle Supplements", "https://ghostlifestyle.com"),
    ("Onnit", "Sports Nutrition", "Total Human Optimization", "https://onnit.com"),
    ("Cymbiotika", "Dietary Supplements", "Liposomal Supplements", "https://cymbiotika.com"),
    ("Garden of Life", "Dietary Supplements", "Organic Vitamins", "https://gardenoflife.com"),
    ("Nordic Naturals", "Dietary Supplements", "Omega-3", "https://nordicnaturals.com"),
    ("NOW Foods", "Dietary Supplements", "Vitamins & Herbs", "https://nowfoods.com"),
    ("Vital Proteins", "Beauty Supplements", "Collagen", "https://www.vitalproteins.com"),
    ("Ancient Nutrition", "Dietary Supplements", "Bone Broth Protein", "https://ancientnutrition.com"),
    ("Organifi", "Dietary Supplements", "Greens & Reds", "https://organifi.com"),
    ("HUM Nutrition", "Beauty Supplements", "Skin & Hair Vitamins", "https://www.humnutrition.com"),
    ("Care/of", "Dietary Supplements", "Personalized Vitamins", "https://takecareof.com"),
    ("Persona Nutrition", "Dietary Supplements", "Personalized Packs", "https://personanutrition.com"),
    ("Needed", "Prenatal Health", "Prenatal Supplements", "https://thisisneeded.com"),
    ("Ritual (Prenatal)", "Prenatal Health", "Prenatal Vitamin", "https://ritual.com/products/essential-prenatal"),
    ("Olly", "Dietary Supplements", "Gummy Vitamins", "https://olly.com"),
    ("SmartyPants Vitamins", "Children's Supplements", "Kids Gummy Vitamins", "https://smartypantsvitamins.com"),
    ("Nature's Bounty", "Dietary Supplements", "Mass Market Vitamins", "https://www.naturesbounty.com"),
    ("Nature Made", "Dietary Supplements", "Vitamins", "https://www.naturemade.com"),
    ("Centrum", "Dietary Supplements", "Multivitamin", "https://www.centrum.com"),
    ("Emergen-C", "Immunity Supplements", "Vitamin C Drink Mix", "https://www.emergenc.com"),
    ("Airborne", "Immunity Supplements", "Immune Support", "https://www.airborne.com"),
    ("Zarbee's", "Children's Supplements", "Children's Wellness", "https://zarbees.com"),
    ("Culturelle", "Gut Health", "Probiotic", "https://www.culturelle.com"),
    ("Align Probiotic", "Gut Health", "Probiotic", "https://www.alignprobiotic.com"),
    ("BioGaia", "Gut Health", "Probiotic Drops", "https://www.biogaia.com"),
    ("MaryRuth Organics", "Dietary Supplements", "Liquid Vitamins", "https://www.maryruthorganics.com"),
    ("MegaFood", "Dietary Supplements", "Whole Food Vitamins", "https://www.megafood.com"),
    ("New Chapter", "Dietary Supplements", "Fermented Vitamins", "https://newchapter.com"),
    ("Rainbow Light", "Dietary Supplements", "Prenatal & Women's", "https://www.rainbowlight.com"),
    ("Solgar", "Dietary Supplements", "Premium Vitamins", "https://www.solgar.com"),
    ("Jarrow Formulas", "Dietary Supplements", "Science-Based Supplements", "https://www.jarrow.com"),
    ("Life Extension", "Dietary Supplements", "Longevity Supplements", "https://www.lifeextension.com"),
    ("Pure Encapsulations", "Dietary Supplements", "Hypoallergenic Supplements", "https://www.pureencapsulations.com"),
    ("Designs for Health", "Dietary Supplements", "Practitioner Line", "https://www.designsforhealth.com"),
    ("Metagenics", "Dietary Supplements", "Medical Nutrition", "https://www.metagenics.com"),
    ("Standard Process", "Dietary Supplements", "Whole Food Supplements", "https://www.standardprocess.com"),
    ("Gaia Herbs", "Herbal Supplements", "Herbal Extracts", "https://www.gaiaherbs.com"),
    ("Herb Pharm", "Herbal Supplements", "Liquid Herbal Extracts", "https://www.herb-pharm.com"),
    ("Nature's Way", "Herbal Supplements", "Herbal Products", "https://www.naturesway.com"),
    ("Swanson Vitamins", "Dietary Supplements", "Value Supplements", "https://www.swansonvitamins.com"),
    ("iHerb (merchant brands)", "Marketplace", "Supplement Retail", "https://www.iherb.com"),
    ("Bulletproof", "Functional Food", "Coffee & MCT", "https://www.bulletproof.com"),
    ("Four Sigmatic", "Functional Beverages", "Mushroom Coffee", "https://us.foursigmatic.com"),
    ("MUD\\WTR", "Functional Beverages", "Mushroom Coffee Alternative", "https://mudwtr.com"),
    ("Ryze Superfoods", "Functional Beverages", "Mushroom Coffee", "https://www.ryzesuperfoods.com"),
    ("Everyday Dose", "Functional Beverages", "Mushroom Coffee", "https://www.everydaydose.com"),
    ("Golde", "Superfoods", "Matcha & Superfood Blends", "https://golde.co"),
    ("Moon Juice", "Wellness", "Adaptogen Supplements", "https://moonjuice.com"),
    ("Sakara Life", "Meal Delivery", "Plant-Based Nutrition", "https://www.sakara.com"),
    ("Daily Harvest", "Functional Food", "Smoothies & Bowls", "https://www.daily-harvest.com"),
    ("Kencko", "Functional Food", "Fruit & Veg Smoothies", "https://www.kencko.com"),
    ("Splendid Spoon", "Meal Delivery", "Plant-Based Meals", "https://www.splendidspoon.com"),
    ("Huel", "Meal Replacement", "Complete Nutrition Shake", "https://huel.com"),
    ("Soylent", "Meal Replacement", "Meal Replacement Drink", "https://soylent.com"),
    ("Ka'Chava", "Meal Replacement", "Superfood Shake", "https://www.kachava.com"),
    ("Orgain", "Plant-Based Nutrition", "Plant Protein", "https://orgain.com"),
    ("Vega", "Plant-Based Nutrition", "Plant Protein", "https://myvega.com"),
    ("PlantFusion", "Plant-Based Nutrition", "Plant Protein", "https://www.plantfusion.com"),
    ("OWYN", "Plant-Based Nutrition", "Plant Protein Shake", "https://liveowyn.com"),
    ("Ripple Foods", "Plant-Based Dairy", "Pea Milk", "https://www.ripplefoods.com"),
    ("Califia Farms", "Plant-Based Dairy", "Plant Milks", "https://www.califiafarms.com"),
    ("Oatly", "Plant-Based Dairy", "Oat Milk", "https://www.oatly.com"),
    ("Minor Figures", "Plant-Based Dairy", "Oat Milk", "https://minorfigures.com"),
    ("NotCo", "Plant-Based Food", "Plant-Based Alternatives", "https://notco.com"),
    ("Beyond Meat", "Plant-Based Food", "Plant-Based Meat", "https://www.beyondmeat.com"),
    ("Impossible Foods", "Plant-Based Food", "Plant-Based Meat", "https://impossiblefoods.com"),
    ("Liquid I.V.", "Functional Beverages", "Hydration Multiplier", "https://www.liquid-iv.com"),
    ("Cure Hydration", "Functional Beverages", "Electrolyte Mix", "https://www.curehydration.com"),
    ("LMNT", "Functional Beverages", "Electrolyte Drink Mix", "https://drinklmnt.com"),
    ("DripDrop", "Functional Beverages", "ORS Hydration", "https://www.dripdrop.com"),
    ("Nuun", "Functional Beverages", "Hydration Tablets", "https://nuunlife.com"),
    ("Gatorade (PepsiCo)", "Sports Beverages", "Sports Drink", "https://www.gatorade.com"),
    ("BodyArmor", "Sports Beverages", "Sports Drink", "https://www.drinkbodyarmor.com"),
    ("Olipop", "Functional Beverages", "Prebiotic Soda", "https://drinkolipop.com"),
    ("Poppi", "Functional Beverages", "Prebiotic Soda", "https://drinkpoppi.com"),
    ("Culture Pop", "Functional Beverages", "Probiotic Soda", "https://drinkculturepop.com"),
    ("Health-Ade", "Fermented Beverages", "Kombucha", "https://health-ade.com"),
    ("GT's Living Foods", "Fermented Beverages", "Kombucha", "https://gtslivingfoods.com"),
    ("Brew Dr. Kombucha", "Fermented Beverages", "Kombucha", "https://brewdrkombucha.com"),
    ("Humm Kombucha", "Fermented Beverages", "Kombucha", "https://www.hummkombucha.com"),
    ("Remedy Drinks", "Fermented Beverages", "Kombucha", "https://www.remedydrinks.com"),
    ("Magic Spoon", "Better-for-You Snacks", "High-Protein Cereal", "https://magicspoon.com"),
    ("Hu Kitchen", "Better-for-You Snacks", "Chocolate & Snacks", "https://hukitchen.com"),
    ("Chomps", "Better-for-You Snacks", "Meat Sticks", "https://chomps.com"),
    ("Epic Provisions", "Better-for-You Snacks", "Meat Bars", "https://www.epicprovisions.com"),
    ("RXBAR", "Better-for-You Snacks", "Protein Bars", "https://www.rxbar.com"),
    ("KIND Snacks", "Better-for-You Snacks", "Snack Bars", "https://www.kindsnacks.com"),
    ("Larabar", "Better-for-You Snacks", "Fruit & Nut Bars", "https://www.larabar.com"),
    ("Clif Bar", "Sports Nutrition", "Energy Bars", "https://www.clifbar.com"),
    ("Perfect Snacks", "Better-for-You Snacks", "Refrigerated Protein Bars", "https://www.perfectsnacks.com"),
    ("GoMacro", "Better-for-You Snacks", "MacroBars", "https://gomacro.com"),
    ("Aloha", "Plant-Based Nutrition", "Plant Protein Bars", "https://aloha.com"),
    ("Barebells", "Sports Nutrition", "Protein Bars", "https://barebells.com"),
    ("Quest Nutrition", "Sports Nutrition", "Protein Bars", "https://www.questnutrition.com"),
    ("Think!", "Better-for-You Snacks", "Protein Bars", "https://thinkproducts.com"),
    ("Primal Kitchen", "Natural Foods", "Sauces & Mayo", "https://www.primalkitchen.com"),
    ("Siete Foods", "Natural Foods", "Grain-Free Tortilla Chips", "https://sietefoods.com"),
    ("Simple Mills", "Natural Foods", "Almond Flour Crackers", "https://www.simplemills.com"),
    ("Annie's (General Mills)", "Natural Foods", "Organic Snacks", "https://www.annies.com"),
    ("Amy's Kitchen", "Natural Foods", "Organic Frozen Meals", "https://www.amys.com"),
    ("Bob's Red Mill", "Natural Foods", "Whole Grain Products", "https://www.bobsredmill.com"),
    ("Nature's Path", "Natural Foods", "Organic Cereal", "https://www.naturespath.com"),
    ("Purely Elizabeth", "Natural Foods", "Granola", "https://purelyelizabeth.com"),
    ("LesserEvil", "Better-for-You Snacks", "Popcorn", "https://lesserevil.com"),
    ("Siete (chips)", "Better-for-You Snacks", "Grain-Free Chips", "https://sietefoods.com"),
    ("The Good Crisp Company", "Better-for-You Snacks", "Clean Ingredient Chips", "https://thegoodcrispcompany.com"),
    ("Banza", "Better-for-You Snacks", "Chickpea Pasta", "https://www.eatbanza.com"),
    ("Caulipower", "Better-for-You Snacks", "Cauliflower Pizza", "https://www.caulipower.com"),
    ("Cleveland Kitchen", "Fermented Foods", "Kimchi & Kraut", "https://www.clevelandkitchen.com"),
    ("Wildbrine", "Fermented Foods", "Sauerkraut", "https://www.wildbrine.com"),
    ("Farmhouse Culture", "Fermented Foods", "Gut Shot", "https://www.farmhouseculture.com"),
    ("The Honey Pot Co", "Feminine Wellness", "Feminine Care", "https://thehoneypot.co"),
    ("Lola", "Feminine Wellness", "Feminine Care", "https://www.mylola.com"),
    ("Corpus Naturals", "Personal Care", "Natural Deodorant", "https://corpusnaturals.com"),
    ("Native", "Personal Care", "Deodorant", "https://www.nativecos.com"),
    ("Schmidt's Naturals", "Personal Care", "Natural Deodorant", "https://schmidts.com"),
    ("Tom's of Maine", "Personal Care", "Natural Oral Care", "https://www.tomsofmaine.com"),
    ("Hello Products", "Oral Care", "Natural Toothpaste", "https://www.hello-products.com"),
    ("Bite Toothpaste Bits", "Oral Care", "Toothpaste Tablets", "https://bitetoothpastebits.com"),
    ("Quip", "Oral Care", "Electric Toothbrush", "https://www.getquip.com"),
    ("Cocofloss", "Oral Care", "Dental Floss", "https://www.cocofloss.com"),
    ("Dr. Bronner's", "Personal Care", "Castile Soap", "https://www.drbronner.com"),
    ("Everyone (EO Products)", "Personal Care", "Natural Body Care", "https://www.everyoneforbodymindandsoul.com"),
    ("Puracy", "Household Product", "Natural Cleaners", "https://puracy.com"),
    ("Seventh Generation", "Household Cleaner", "Plant-Based Cleaners", "https://www.seventhgeneration.com"),
    ("Mrs. Meyer's", "Household Cleaner", "Aromatherapy Cleaners", "https://www.mrsmeyers.com"),
    ("Method", "Household Cleaner", "Design-Led Cleaners", "https://methodproducts.com"),
    ("Branch Basics", "Household Cleaner", "Concentrate Cleaning", "https://branchbasics.com"),
    ("Blueland", "Household Cleaner", "Refillable Cleaners", "https://www.blueland.com"),
    ("Grove Collaborative", "Household Product", "Natural Home Marketplace", "https://www.grove.co"),
    ("Thrive Market", "Marketplace", "Natural Products Retail", "https://thrivemarket.com"),
    ("Public Goods", "Household Product", "Minimal Ingredient Essentials", "https://www.publicgoods.com"),
    ("The Ordinary", "Cosmetic", "Clinical Skincare", "https://theordinary.com"),
    ("Paula's Choice", "Cosmetic", "Evidence-Based Skincare", "https://www.paulaschoice.com"),
    ("CeraVe", "Cosmetic", "Dermatologist Skincare", "https://www.cerave.com"),
    ("La Roche-Posay", "Cosmetic", "Sensitive Skin Care", "https://www.laroche-posay.us"),
    ("Supergoop!", "Suncare", "SPF Skincare", "https://supergoop.com"),
    ("Coola", "Suncare", "Organic Suncare", "https://coola.com"),
    ("Sun Bum", "Suncare", "Sunscreen", "https://www.sunbum.com"),
    ("EltaMD", "Suncare", "Derm Sunscreen", "https://eltamd.com"),
    ("Tatcha", "Cosmetic", "Luxury Skincare", "https://www.tatcha.com"),
    ("Glow Recipe", "Cosmetic", "Fruit-Powered Skincare", "https://www.glowrecipe.com"),
    ("Youth to the People", "Cosmetic", "Superfood Skincare", "https://www.youthtothepeople.com"),
    ("Herbivore Botanicals", "Cosmetic", "Natural Skincare", "https://www.herbivorebotanicals.com"),
    ("OSEA Malibu", "Cosmetic", "Seaweed Skincare", "https://oseamalibu.com"),
    ("Drunk Elephant", "Cosmetic", "Clean-Clinical Skincare", "https://www.drunkelephant.com"),
    ("Summer Fridays", "Cosmetic", "Skincare & Lip Care", "https://summerfridays.com"),
    ("Kosas", "Cosmetic", "Clean Makeup", "https://kosas.com"),
    ("Ilia Beauty", "Cosmetic", "Clean Makeup", "https://iliabeauty.com"),
    ("RMS Beauty", "Cosmetic", "Organic Makeup", "https://www.rmsbeauty.com"),
    ("Saie", "Cosmetic", "Clean Makeup", "https://saiehello.com"),
    ("Merit", "Cosmetic", "Minimal Makeup", "https://www.meritbeauty.com"),
    ("Jones Road Beauty", "Cosmetic", "Clean Makeup", "https://www.jonesroadbeauty.com"),
    ("Fenty Skin", "Cosmetic", "Inclusive Skincare", "https://fentyskin.com"),
    ("The Inkey List", "Cosmetic", "Affordable Actives", "https://www.theinkeylist.com"),
    ("Good Molecules", "Cosmetic", "Affordable Skincare", "https://goodmolecules.com"),
    ("Naturium", "Cosmetic", "Biocompatible Skincare", "https://naturium.com"),
    ("Topicals", "Cosmetic", "Chronic Skin Solutions", "https://www.mytopicals.com"),
    ("Starface", "Cosmetic", "Acne Care", "https://starface.world"),
    ("Hero Cosmetics", "Cosmetic", "Acne Patches", "https://www.herocosmetics.us"),
    ("Differin (Galderma)", "Cosmetic", "OTC Acne Treatment", "https://www.differin.com"),
    ("Versed", "Cosmetic", "Drugstore Clean Skincare", "https://versedskin.com"),
    ("Kinship", "Cosmetic", "Clean Skincare", "https://lovekinship.com"),
    ("Biossance", "Cosmetic", "Squalane Skincare", "https://biossance.com"),
    ("Pipette", "Baby Product", "Baby Clean Care", "https://pipettebaby.com"),
    ("Honest Company", "Baby Product", "Baby & Home", "https://www.honest.com"),
    ("Babyganics", "Baby Product", "Baby Care", "https://www.babyganics.com"),
    ("Earth's Best", "Children's Food", "Organic Baby Food", "https://www.earthsbest.com"),
    ("Happy Baby Organics", "Children's Food", "Organic Baby Food", "https://www.happyfamilyorganics.com"),
    ("Once Upon a Farm", "Children's Food", "Cold-Pressed Baby Food", "https://www.onceuponafarmorganics.com"),
    ("Serenity Kids", "Children's Food", "Meat & Veg Baby Pouches", "https://myserenitykids.com"),
    ("Yumi", "Children's Food", "Baby Nutrition", "https://www.helloyumi.com"),
    ("Little Spoon", "Children's Food", "Fresh Baby Meals", "https://www.littlespoon.com"),
    ("Gerber (Nestlé)", "Children's Food", "Baby Food", "https://www.gerber.com"),
    ("Plum Organics", "Children's Food", "Organic Baby Food", "https://www.plumorganics.com"),
    ("Blue Buffalo", "Pet Food", "Natural Pet Food", "https://bluebuffalo.com"),
    ("The Farmer's Dog", "Pet Food", "Fresh Dog Food", "https://www.thefarmersdog.com"),
    ("Ollie", "Pet Food", "Fresh Dog Food", "https://www.myollie.com"),
    ("Nom Nom", "Pet Food", "Fresh Pet Food", "https://www.nomnomnow.com"),
    ("JustFoodForDogs", "Pet Food", "Fresh Dog Food", "https://www.justfoodfordogs.com"),
    ("Open Farm", "Pet Food", "Ethically Sourced Pet Food", "https://openfarmpet.com"),
    ("The Honest Kitchen", "Pet Food", "Dehydrated Pet Food", "https://www.thehonestkitchen.com"),
    ("Stella & Chewy's", "Pet Food", "Raw Pet Food", "https://www.stellaandchewys.com"),
    ("Instinct Pet Food", "Pet Food", "Raw & Natural Pet", "https://instinctpetfood.com"),
    ("Wellness Pet Company", "Pet Food", "Natural Pet Food", "https://www.wellnesspetfood.com"),
    ("Nutramax (Cosequin)", "Pet Supplement", "Joint Supplement for Pets", "https://www.nutramaxlabs.com"),
    ("Zesty Paws", "Pet Supplement", "Pet Supplements", "https://zestypaws.com"),
    ("PetHonesty", "Pet Supplement", "Pet Supplements", "https://www.pethonesty.com"),
    ("Native Pet", "Pet Supplement", "Dog Supplements", "https://nativepet.com"),
    ("Finn", "Pet Supplement", "Allergy & Hip Supplements", "https://petfinn.com"),
    ("Chewy (private labels)", "Pet Care", "Pet Retail", "https://www.chewy.com"),
    ("BarkBox", "Pet Care", "Dog Subscription", "https://www.barkbox.com"),
    # India - supplements, ayurvedic, DTC beauty
    ("Mamaearth", "Personal Care", "Toxin-Free Personal Care", "https://mamaearth.in"),
    ("Wow Skin Science", "Personal Care", "Natural Beauty", "https://www.buywow.in"),
    ("Plum Goodness", "Cosmetic", "Vegan Beauty", "https://plumgoodness.com"),
    ("Minimalist", "Cosmetic", "Active-Based Skincare", "https://beminimalist.co"),
    ("Dot & Key", "Cosmetic", "Skincare", "https://www.dotandkey.com"),
    ("mCaffeine", "Personal Care", "Caffeine Personal Care", "https://www.mcaffeine.com"),
    ("Sugar Cosmetics", "Cosmetic", "Makeup", "https://www.sugarcosmetics.com"),
    ("Nykaa (private brands)", "Cosmetic", "Beauty Retail", "https://www.nykaa.com"),
    ("Kapiva", "Ayurvedic Wellness", "Ayurvedic Juices & Supplements", "https://kapiva.in"),
    ("Oziva", "Plant-Based Nutrition", "Plant Protein & Herbs", "https://www.oziva.in"),
    ("Wellbeing Nutrition", "Dietary Supplements", "Melts & Supplements", "https://wellbeingnutrition.com"),
    ("Plix Life", "Weight Management", "Plant-Based Supplements", "https://www.plixlife.com"),
    ("Fast&Up", "Sports Nutrition", "Sports Nutrition India", "https://www.fastandup.in"),
    ("HealthKart", "Marketplace", "Supplement Retail India", "https://www.healthkart.com"),
    ("MuscleBlaze", "Sports Nutrition", "Sports Supplements India", "https://www.muscleblaze.com"),
    ("TrueBasics", "Dietary Supplements", "Clean Supplements India", "https://www.truebasics.com"),
    ("Himalaya Wellness", "Ayurvedic Wellness", "Ayurvedic Products", "https://himalayawellness.in"),
    ("Dabur", "Ayurvedic Wellness", "Ayurvedic & FMCG", "https://www.dabur.com"),
    ("Patanjali", "Ayurvedic Wellness", "Ayurvedic FMCG", "https://www.patanjaliayurved.net"),
    ("Baidyanath", "Ayurvedic Wellness", "Ayurvedic Medicines", "https://www.baidyanath.co.in"),
    ("Zandu", "Ayurvedic Wellness", "Ayurvedic Remedies", "https://zanducare.com"),
    ("Organic India", "Herbal Supplements", "Tulsi & Supplements", "https://organicindia.com"),
    ("Nutrilite (Amway India)", "Dietary Supplements", "Vitamins India", "https://www.amway.in"),
    ("GNC India", "Dietary Supplements", "Sports & Wellness Retail", "https://www.gnc.co.in"),
    ("Setu Nutrition", "Dietary Supplements", "Science-Led Supplements", "https://setu.in"),
    ("Boldfit", "Sports Nutrition", "Fitness Supplements India", "https://boldfit.in"),
    ("Neuherbs", "Dietary Supplements", "Weight & Wellness", "https://neuherbs.com"),
    ("Gritzo", "Children's Supplements", "Kids Nutrition India", "https://gritzo.com"),
    ("Beardo", "Men's Grooming", "Men's Grooming", "https://beardo.in"),
    ("The Man Company", "Men's Grooming", "Men's Grooming", "https://www.themancompany.com"),
    ("Ustraa", "Men's Grooming", "Men's Grooming", "https://www.ustraa.com"),
    ("Boat Lifestyle (wellness SKUs)", "Consumer Electronics", "Wearables & Wellness", "https://www.boat-lifestyle.com"),
    ("Phab", "Sports Nutrition", "Protein India", "https://phab.in"),
    ("Yoga Bar", "Better-for-You Snacks", "Snack Bars India", "https://www.yogabars.in"),
    ("True Elements", "Natural Foods", "Clean Label Foods India", "https://trueelements.com"),
    ("Soulfull", "Natural Foods", "Millets & Cereals", "https://www.soulfull.co.in"),
    ("Slurrp Farm", "Children's Food", "Kids Healthy Food India", "https://slurrpfarm.com"),
    ("Licious", "Food", "Fresh Meat D2C", "https://www.licious.in"),
    ("Country Delight", "Food", "Fresh Dairy D2C", "https://countrydelight.in"),
    ("Raw Pressery", "Functional Beverages", "Cold-Pressed Juice India", "https://www.rawpressery.com"),
    ("Paper Boat", "Beverage", "Traditional Beverages", "https://www.paperboatfoods.com"),
    ("Epigamia", "Functional Food", "Greek Yogurt India", "https://epigamia.com"),
    ("Yakult", "Gut Health", "Probiotic Drink", "https://www.yakult.co.in"),
    ("Protinex", "Dietary Supplements", "Protein Supplement India", "https://www.protinex.in"),
    ("Ensure (Abbott India)", "Dietary Supplements", "Adult Nutrition", "https://www.ensure.in"),
    ("Horlicks (HUL)", "Functional Food", "Nutrition Beverage", "https://www.horlicks.in"),
    ("Saffola (Marico)", "Functional Food", "Heart Health Foods", "https://www.saffola.in"),
    ("Truecaller Ads wellness DTC", "Emerging DTC", "Digital-First Brand", ""),
    # UK / EU brands
    ("Holland & Barrett", "Marketplace", "Health Retail UK", "https://www.hollandandbarrett.com"),
    ("Myprotein", "Sports Nutrition", "Sports Nutrition UK", "https://www.myprotein.com"),
    ("Bulk", "Sports Nutrition", "Sports Nutrition UK", "https://www.bulk.com"),
    ("PhD Nutrition", "Sports Nutrition", "Sports Nutrition UK", "https://www.phd.com"),
    ("Grenade", "Sports Nutrition", "Protein Bars UK", "https://www.grenade.com"),
    ("Science in Sport", "Sports Nutrition", "Endurance Nutrition", "https://www.scienceinsport.com"),
    ("Optimum Nutrition (Glanbia)", "Sports Nutrition", "Whey Protein", "https://www.optimumnutrition.com"),
    ("Revolution Beauty", "Cosmetic", "Affordable Beauty UK", "https://www.revolutionbeauty.com"),
    ("The Body Shop", "Cosmetic", "Ethical Beauty", "https://www.thebodyshop.com"),
    ("Lush", "Personal Care", "Fresh Handmade Cosmetics", "https://www.lush.com"),
    ("Neal's Yard Remedies", "Personal Care", "Organic Remedies UK", "https://www.nealsyardremedies.com"),
    ("Pukka Herbs", "Herbal Tea", "Organic Herbal Tea", "https://www.pukkaherbs.com"),
    ("Teapigs", "Herbal Tea", "Premium Tea UK", "https://www.teapigs.co.uk"),
    ("Clipper Teas", "Herbal Tea", "Organic Tea", "https://www.clipper-teas.com"),
    ("Innocent Drinks", "Beverage", "Smoothies UK", "https://www.innocentdrinks.co.uk"),
    ("Plenish", "Functional Beverages", "Cold-Pressed Juice UK", "https://www.plenishcleanse.com"),
    ("Purition", "Meal Replacement", "Wholefood Shakes UK", "https://www.purition.co.uk"),
    ("Innermost", "Dietary Supplements", "Targeted Supplements UK", "https://www.liveinnermost.com"),
    ("Form Nutrition", "Plant-Based Nutrition", "Plant Protein UK", "https://formnutrition.com"),
    ("Vivo Life", "Plant-Based Nutrition", "Plant Supplements UK", "https://www.vivolife.com"),
    ("Motion Nutrition", "Sports Nutrition", "Recovery Supplements UK", "https://motionnutrition.com"),
    ("Nuzest", "Plant-Based Nutrition", "Clean Protein", "https://nuzest.com"),
    ("Bare Biology", "Dietary Supplements", "Omega-3 UK", "https://www.barebiology.com"),
    ("Wild Nutrition", "Dietary Supplements", "Food-Grown Supplements UK", "https://www.wildnutrition.com"),
    ("Equi London", "Beauty Supplements", "Beauty Supplements UK", "https://www.equi.london"),
    ("Ancient + Brave", "Superfoods", "Cacao & Collagen UK", "https://ancientandbrave.earth"),
    ("Dirtea", "Functional Beverages", "Mushroom Drinks UK", "https://dirtea.com"),
    ("Trip Drinks", "Functional Beverages", "CBD / Adaptogen Drinks UK", "https://tripdrinks.co"),
    ("Plenish (EU)", "Functional Beverages", "Functional Drinks", "https://www.plenishcleanse.com"),
    ("YFood", "Meal Replacement", "Balanced Drink EU", "https://yfood.eu"),
    ("Feed.", "Meal Replacement", "Complete Food EU", "https://feed.co"),
    ("Foodspring", "Sports Nutrition", "Fitness Nutrition DE", "https://www.foodspring.de"),
    ("ESN", "Sports Nutrition", "Elite Sports Nutrition DE", "https://www.esn.com"),
    ("More Nutrition", "Sports Nutrition", "Sports Supplements DE", "https://morenutrition.de"),
    ("Nature Love", "Dietary Supplements", "Supplements DE", "https://nature-love.de"),
    ("Sunday Natural", "Dietary Supplements", "Premium Supplements DE", "https://www.sunday.de"),
    ("Nu3", "Dietary Supplements", "Sports Nutrition DE", "https://www.nu3.de"),
    ("Decathlon Nutrition", "Sports Nutrition", "Sports Nutrition FR", "https://www.decathlon.com"),
    ("Isostar", "Sports Nutrition", "Sports Nutrition FR", "https://www.isostar.fr"),
    ("Nutri&Co", "Dietary Supplements", "French Supplements", "https://nutriandco.com"),
    ("Juvamine", "Dietary Supplements", "Vitamins FR", "https://www.juvamine.com"),
    ("Arkopharma", "Herbal Supplements", "Phytotherapy FR", "https://www.arkopharma.com"),
    ("Pranarom", "Aromatherapy", "Essential Oils BE", "https://www.pranarom.com"),
    ("Australian NaturalCare", "Dietary Supplements", "Supplements AU", "https://www.ausnaturalcare.com.au"),
    ("Blackmores", "Dietary Supplements", "Vitamins AU", "https://www.blackmores.com.au"),
    ("Swisse", "Dietary Supplements", "Premium Wellness AU", "https://www.swisse.com"),
    ("BioCeuticals", "Dietary Supplements", "Practitioner AU", "https://www.bioceuticals.com.au"),
    ("JSHealth Vitamins", "Beauty Supplements", "Vitamins AU", "https://jshealthvitamins.com"),
    ("The Beauty Chef", "Gut Health", "Inner Beauty AU", "https://thebeautychef.com"),
    ("WelleCo", "Superfoods", "Super Elixir AU", "https://welleco.com"),
    ("Tropeaka", "Plant-Based Nutrition", "Plant Protein AU", "https://tropeaka.com.au"),
    ("Amazon private label (Solimo)", "Marketplace", "Amazon Supplements", "https://www.amazon.com"),
    ("Amazon private label (Amazon Basics)", "Marketplace", "Amazon Wellness", "https://www.amazon.com"),
    ("Walmart Equate", "Dietary Supplements", "Private Label Vitamins", "https://www.walmart.com"),
    ("Target Good & Gather", "Natural Foods", "Private Label Food", "https://www.target.com"),
    ("Costco Kirkland Supplements", "Dietary Supplements", "Private Label", "https://www.costco.com"),
    ("Trader Joe's Supplements", "Dietary Supplements", "Private Label", "https://www.traderjoes.com"),
    ("Whole Foods 365", "Natural Foods", "Private Label", "https://www.wholefoodsmarket.com"),
    ("Sprouts Farmers Market PL", "Natural Foods", "Private Label", "https://www.sprouts.com"),
    ("Erewhon Market brands", "Natural Foods", "Premium Grocery LA", "https://www.erewhonmarket.com"),
    ("Natural Grocers PL", "Natural Foods", "Natural Retail", "https://www.naturalgrocers.com"),
    ("Fresh Thyme", "Natural Foods", "Natural Grocery", "https://www.freshthyme.com"),
    ("GNC", "Marketplace", "Supplement Retail US", "https://www.gnc.com"),
    ("Vitamin Shoppe", "Marketplace", "Supplement Retail US", "https://www.vitaminshoppe.com"),
    ("Vitacost", "Marketplace", "Online Supplements", "https://www.vitacost.com"),
    ("Bodybuilding.com", "Marketplace", "Fitness Retail", "https://www.bodybuilding.com"),
    ("Nutrabolt (C4)", "Sports Nutrition", "Energy & Pre-Workout", "https://www.nutrabolt.com"),
    ("Cellucor", "Sports Nutrition", "C4 Pre-Workout", "https://cellucor.com"),
    ("BPI Sports", "Sports Nutrition", "Sports Supplements", "https://bpisports.com"),
    ("Redcon1", "Sports Nutrition", "Military-Inspired Supplements", "https://redcon1.com"),
    ("Alani Nu", "Sports Nutrition", "Women's Supplements", "https://www.alaninu.com"),
    ("Bloom Nutrition", "Sports Nutrition", "Greens & Pre-Workout", "https://www.bloomnu.com"),
    ("PEScience", "Sports Nutrition", "Select Protein", "https://pescience.com"),
    ("Rule One Proteins", "Sports Nutrition", "R1 Protein", "https://ruleoneproteins.com"),
    ("Dymatize", "Sports Nutrition", "ISO100 Whey", "https://www.dymatize.com"),
    ("Isopure", "Sports Nutrition", "Clear Protein", "https://www.isopurecompany.com"),
    ("MuscleTech", "Sports Nutrition", "Mass & Performance", "https://www.muscletech.com"),
    ("BSN", "Sports Nutrition", "Syntha-6 Protein", "https://www.bsnonline.net"),
    ("GAT Sport", "Sports Nutrition", "Sport Supplements", "https://gatsport.com"),
    ("EVLution Nutrition", "Sports Nutrition", "Stacked Supplements", "https://evlnutrition.com"),
    ("Nutrex Research", "Sports Nutrition", "Hardcore Supplements", "https://nutrex.com"),
    ("Universal Nutrition", "Sports Nutrition", "Animal Pak", "https://www.universalnutrition.com"),
    ("JYM Supplement Science", "Sports Nutrition", "Science-Based Supplements", "https://www.jymsupplementscience.com"),
    ("KetoLogic", "Weight Management", "Keto Supplements", "https://ketologic.com"),
    ("Perfect Keto", "Weight Management", "Keto Products", "https://perfectketo.com"),
    ("Chomps (keto angle)", "Better-for-You Snacks", "Keto Meat Sticks", "https://chomps.com"),
    ("ChocZero", "Better-for-You Snacks", "Keto Chocolate", "https://www.choczero.com"),
    ("Lakanto", "Natural Foods", "Keto Sweetener", "https://www.lakanto.com"),
    ("SmartSweets", "Better-for-You Snacks", "Low-Sugar Candy", "https://www.smartsweets.com"),
    ("HighKey", "Better-for-You Snacks", "Keto Snacks", "https://highkey.com"),
    ("Chobani", "Functional Food", "Greek Yogurt", "https://www.chobani.com"),
    ("Siggi's", "Functional Food", "Icelandic Yogurt", "https://www.siggis.com"),
    ("Noosa", "Functional Food", "Finest Yoghurt", "https://www.noosayoghurt.com"),
    ("Maple Hill", "Functional Food", "Grass-Fed Dairy", "https://www.maplehill.com"),
    ("Stonyfield Organic", "Functional Food", "Organic Yogurt", "https://www.stonyfield.com"),
    ("Tillamook", "Food", "Dairy Co-op", "https://www.tillamook.com"),
    ("Kerrygold", "Food", "Grass-Fed Butter", "https://www.kerrygold.com"),
    ("Applegate", "Food", "Natural & Organic Meats", "https://applegate.com"),
    ("Applegate Organics", "Food", "Organic Deli Meats", "https://applegate.com"),
    ("Teton Waters Ranch", "Food", "Grass-Fed Hot Dogs", "https://www.tetonwatersranch.com"),
    ("Force of Nature", "Food", "Regenerative Meats", "https://forceofnature.com"),
    ("White Oak Pastures", "Food", "Regenerative Farm", "https://www.whiteoakpastures.com"),
    ("Thrive Market brands", "Marketplace", "Private Label Natural", "https://thrivemarket.com"),
    ("Brandless (relaunch)", "Household Product", "Value Essentials", "https://www.brandless.com"),
    ("Brandless wellness", "Dietary Supplements", "Affordable Supplements", "https://www.brandless.com"),
    ("Rae Wellness", "Women's Wellness", "Women's Supplements", "https://raewellness.co"),
    ("Love Wellness", "Women's Wellness", "Women's Health DTC", "https://lovewellness.com"),
    ("Uqora", "Women's Wellness", "UTI Prevention", "https://uqora.com"),
    ("Ritual (Synbiotic)", "Gut Health", "Synbiotic", "https://ritual.com"),
    ("Pendulum", "Gut Health", "Medical Probiotic", "https://pendulumlife.com"),
    ("Jetson", "Gut Health", "Seasonal Probiotics", "https://jetsonjourney.com"),
    ("Flore", "Gut Health", "Personalized Probiotic", "https://flore.com"),
    ("Sun Genomics", "Gut Health", "Custom Probiotic", "https://sungenomics.com"),
    ("Viome", "Health Technology", "Gut Testing", "https://www.viome.com"),
    ("InsideTracker", "Health Technology", "Blood Analytics", "https://www.insidetracker.com"),
    ("Levels", "Health Technology", "Metabolic Health", "https://www.levels.com"),
    ("Oura (partnerships)", "Health Technology", "Sleep & Recovery", "https://ouraring.com"),
    ("Whoop", "Fitness Service", "Recovery Wearable", "https://www.whoop.com"),
    ("Peloton supplements angle", "Fitness Service", "Fitness Ecosystem", "https://www.onepeloton.com"),
    ("Barry's x supplement collabs", "Fitness Service", "Studio Fitness", "https://www.barrys.com"),
    ("F45 supplement partners", "Fitness Service", "Franchise Fitness", "https://f45training.com"),
    ("Equinox media wellness", "Fitness Service", "Premium Fitness", "https://www.equinox.com"),
    ("Influencer: Logan Paul (Prime)", "Functional Beverages", "Hydration Drink", "https://drinkprime.com"),
    ("Influencer: KSI (Prime)", "Functional Beverages", "Sports Hydration", "https://drinkprime.com"),
    ("Influencer: Chamberlain Coffee", "Functional Beverages", "Coffee Brand", "https://www.chamberlaincoffee.com"),
    ("Influencer: Chamberlain Coffee pods", "Functional Beverages", "Coffee Products", "https://www.chamberlaincoffee.com"),
    ("TikTok Shop supplement sellers", "Emerging DTC", "Social Commerce Supplements", ""),
    ("Reddit r/Supplements community brands", "Emerging DTC", "Community-Loved Brands", ""),
    ("Reddit r/BeautyGuruChatter indie", "Cosmetic", "Indie Beauty", ""),
    ("LinkedIn DTC founder brands", "Emerging DTC", "Founder-Led Wellness", ""),
    ("Instagram #supplementbrand", "Emerging DTC", "Instagram DTC", ""),
    ("Instagram #cleanbeauty", "Cosmetic", "Clean Beauty DTC", ""),
    ("TikTok #healthtok brands", "Emerging DTC", "HealthTok Products", ""),
    ("LinkedIn nutraceutical startups", "Dietary Supplements", "B2B Supplement Startups", ""),
    ("Puori", "Dietary Supplements", "Clean Supplements EU", "https://puori.com"),
    ("Nikalab", "Dietary Supplements", "Premium Supplements PL", "https://nikalab.pl"),
    ("Trace Minerals", "Dietary Supplements", "Trace Mineral Drops", "https://www.traceminerals.com"),
    ("Naked Nutrition", "Sports Nutrition", "Minimal Ingredient Protein", "https://nakednutrition.com"),
    ("Puori (US)", "Dietary Supplements", "Purity-Tested Supplements", "https://puori.com"),
    ("Puori (collagen)", "Beauty Supplements", "Collagen EU", "https://puori.com"),
    ("Natural Vitality (CALM)", "Sleep Supplements", "Magnesium Drink", "https://www.naturalvitality.com"),
    ("Calm by Natural Vitality", "Sleep Supplements", "Magnesium Supplement", "https://www.naturalvitality.com"),
    ("Nested Naturals", "Sleep Supplements", "Sleep Support", "https://nestednaturals.com"),
    ("Proper", "Sleep Supplements", "Sleep Wellness", "https://www.proper.co"),
    ("Remrise", "Sleep Supplements", "Personalized Sleep", "https://www.remrise.com"),
    ("The Nue Co", "Dietary Supplements", "Functional Supplements", "https://thenueco.com"),
    ("Arrae", "Women's Wellness", "Bloat & Wellness", "https://www.arrae.com"),
    ("WelleCo (US)", "Superfoods", "Super Elixir", "https://welleco.com"),
    ("Agent Nateur", "Cosmetic", "Holistic Beauty", "https://agentnateur.com"),
    ("Anima Mundi", "Herbal Supplements", "Herbal Apothecary", "https://animamundiherbals.com"),
    ("Moon Juice (US)", "Wellness", "Adaptogens", "https://moonjuice.com"),
    ("Sakara (supplements)", "Dietary Supplements", "Metabolism Super Bar", "https://www.sakara.com"),
    ("Erewhon private label", "Natural Foods", "Premium Private Label", "https://www.erewhonmarket.com"),
    ("Erewhon tonics", "Functional Beverages", "Wellness Tonics", "https://www.erewhonmarket.com"),
    ("Clean Juice", "Functional Beverages", "Juice Bar Franchise", "https://www.cleanjuice.com"),
    ("Pressed Juicery", "Functional Beverages", "Juice & Soft Serve", "https://www.pressed.com"),
    ("Juice Press", "Functional Beverages", "Organic Juice NYC", "https://www.juicepress.com"),
    ("Project Juice", "Functional Beverages", "Organic Juice", "https://www.projectjuice.com"),
    ("Suja Organic", "Functional Beverages", "Cold-Pressed Juice", "https://www.sujajuice.com"),
    ("Evolution Fresh", "Functional Beverages", "Starbucks Juice", "https://www.evolutionfresh.com"),
    ("Naked Juice", "Beverage", "Smoothie Juice", "https://www.nakedjuice.com"),
    ("Bolthouse Farms", "Beverage", "Better-for-You Beverages", "https://www.bolthouse.com"),
    ("Harmless Harvest", "Beverage", "Coconut Water", "https://harmlessharvest.com"),
    ("Vita Coco", "Beverage", "Coconut Water", "https://www.vitacoco.com"),
    ("Zico", "Beverage", "Coconut Water", "https://www.zico.com"),
    ("WTRMLN WTR", "Beverage", "Hydration Beverage", "https://wtrmlnwtr.com"),
    ("BevNet featured brands", "Emerging DTC", "Beverage Innovators", "https://www.bevnet.com"),
    ("BevNet Sparkling", "Functional Beverages", "New Beverage Brands", "https://www.bevnet.com"),
    ("NutraIngredients featured", "Dietary Supplements", "Industry Innovators", "https://www.nutraingredients.com"),
    ("SupplySide West exhibitors", "Dietary Supplements", "Trade Show Leads", "https://www.supplysideglobal.com"),
    ("Natural Products Expo brands", "Natural Foods", "Expo West Exhibitors", "https://www.expowest.com"),
    ("Expo East natural brands", "Natural Foods", "Expo East Exhibitors", "https://www.expoeast.com"),
    ("Influencer: AG1 competitors", "Dietary Supplements", "Greens Category", "https://drinkag1.com"),
    ("Influencer skincare DTC", "Cosmetic", "Creator-Owned Beauty", ""),
    ("TikTok viral supplement", "Emerging DTC", "Viral TikTok Supplement", ""),
    ("LinkedIn clean label food", "Natural Foods", "Clean Label CPG", ""),
    ("Reddit r/nutrition indie", "Dietary Supplements", "Nutrition Community Picks", ""),
    ("Reddit r/IndianSkincareAddicts", "Cosmetic", "India Beauty Community", ""),
    ("Reddit r/Ayurveda products", "Ayurvedic Wellness", "Ayurveda Products", ""),
    ("Instagram India wellness", "Ayurvedic Wellness", "India Instagram DTC", ""),
    ("TikTok India supplements", "Dietary Supplements", "India TikTok Wellness", ""),
    ("LinkedIn India D2C FMCG", "Emerging DTC", "India D2C Brands", ""),
]
# fmt: on

REDDIT_DEFAULTS = {
    "Dietary Supplements": "r/Supplements",
    "Sports Nutrition": "r/fitness",
    "Cosmetic": "r/SkincareAddiction",
    "Ayurvedic Wellness": "r/Ayurveda",
    "Pet Food": "r/dogs",
    "Pet Supplement": "r/dogs",
    "Functional Beverages": "r/nutrition",
    "Children's Food": "r/Parenting",
    "Emerging DTC": "r/Entrepreneur",
}


def get_prospect_seed_data() -> list[Prospect]:
    rows: list[Prospect] = []
    for entry in BRANDS:
        if len(entry) < 4:
            continue
        name, sector, product, website = entry[0], entry[1], entry[2], entry[3]
        reddit = REDDIT_DEFAULTS.get(sector, "")
        source = "Public brand website / industry research"
        if name.startswith("Reddit "):
            source = "Reddit community research"
        elif name.startswith("Instagram "):
            source = "Instagram public hashtag research"
        elif name.startswith("TikTok "):
            source = "TikTok public hashtag research"
        elif name.startswith("LinkedIn "):
            source = "LinkedIn company search"
        rows.append(_row(name, sector, product, website, reddit=reddit, source=source))

    return rows[:400]


if __name__ == "__main__":
    data = get_prospect_seed_data()
    print(len(data))