import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { analyzeClaim } from "../lib/analyzeClaim";
import { matchClaimRules } from "../lib/claimRules";
import { runCopilotFeatureTests } from "../lib/complianceCopilot";
import { EXPANDED_REGRESSION_CASES } from "../lib/expandedRegressionCases";

type PatternStat = {
  phrase: string;
  severity: "high" | "medium";
  count: number;
  categories: string[];
};

const patternMap = new Map<string, PatternStat>();
let classificationPassed = 0;
let rewritePassed = 0;
let highCases = 0;

for (const testCase of EXPANDED_REGRESSION_CASES) {
  const analysis = analyzeClaim({
    claimText: testCase.claim,
    productCategory: testCase.category,
    ingredients: ["Representative ingredient"],
    market: testCase.market,
    contextType: testCase.context || "Website",
  });

  const rewriteAnalysis = analyzeClaim({
    claimText: analysis.saferRewrite,
    productCategory: testCase.category,
    ingredients: ["Representative ingredient"],
    market: testCase.market,
    contextType: testCase.context || "Website",
  });

  if (analysis.riskLevel === testCase.expected) classificationPassed++;
  if (testCase.expected === "high") {
    highCases++;
    if (rewriteAnalysis.riskLevel !== "high") rewritePassed++;
  }

  for (const rule of matchClaimRules(testCase.claim, testCase.category, testCase.market)) {
    const key = `${rule.severity}:${rule.phrase}`;
    const existing = patternMap.get(key) || {
      phrase: rule.displayPhrase || rule.phrase,
      severity: rule.severity,
      count: 0,
      categories: [],
    };
    existing.count++;
    if (!existing.categories.includes(testCase.category)) existing.categories.push(testCase.category);
    patternMap.set(key, existing);
  }
}

const topPatterns = [...patternMap.values()]
  .sort((a, b) => b.count - a.count)
  .slice(0, 25);

const copilotTests = runCopilotFeatureTests();
const report = {
  generatedAt: new Date().toISOString(),
  totalCases: EXPANDED_REGRESSION_CASES.length,
  classificationAccuracy: `${classificationPassed}/${EXPANDED_REGRESSION_CASES.length}`,
  rewriteSafety: highCases ? `${rewritePassed}/${highCases}` : "n/a",
  copilotFeatureTests: `${copilotTests.filter((test) => test.passed).length}/${copilotTests.length}`,
  topPatterns,
  copilotTests,
};

const reportPath = resolve(process.cwd(), "lib", "copilotTrainingReport.json");
writeFileSync(reportPath, `${JSON.stringify(report, null, 2)}\n`, "utf8");

const learningsPath = resolve(process.cwd(), "lib", "copilotLearnings.ts");
const learningsSource = `/** Auto-generated by scripts/train-copilot-model.ts — do not edit manually. */\n\nexport const COPILOT_TRAINING = ${JSON.stringify({
  generatedAt: report.generatedAt,
  totalCases: report.totalCases,
  classificationAccuracy: report.classificationAccuracy,
  rewriteSafety: report.rewriteSafety,
  copilotFeatureTests: report.copilotFeatureTests,
  topPatterns: topPatterns.map((pattern) => ({
    phrase: pattern.phrase,
    severity: pattern.severity,
    hits: pattern.count,
    categories: pattern.categories.slice(0, 5),
  })),
}, null, 2)} as const;\n`;
writeFileSync(learningsPath, learningsSource, "utf8");

console.log("Copilot training complete");
console.log(`Classification: ${report.classificationAccuracy}`);
console.log(`Rewrite safety: ${report.rewriteSafety}`);
console.log(`Copilot features: ${report.copilotFeatureTests}`);
console.log(`Report: ${reportPath}`);
console.log(`Learnings: ${learningsPath}`);